    "what": [
      "The representation of what a machine learning system has learned from the training data.",
      "A statistical model is a mathematical model that embodies a set of statistical assumptions concerning the generation of sample data (and similar data from a larger population). A statistical model represents, often in considerably idealized form, the data-generating process. A statistical model is usually specified as a mathematical relationship between one or more random variables and other non-random variables. As such, a statistical model is 'a formal representation of a theory'", 
      "All statistical hypothesis tests and all statistical estimators are derived via statistical models. More generally, statistical models are part of the foundation of statistical inference.",
      "A mathematical model is a description of a system using mathematical concepts and language. The process of developing a mathematical model is termed mathematical modeling. Mathematical models are used in the natural sciences (such as physics, biology, earth science, chemistry) and engineering disciplines (such as computer science, electrical engineering), as well as in non-physical systems such as the social sciences (such as economics, psychology, sociology, political science)",
       "[related] representation, a machine learning system, learned from, the training data. a statistical model, mathematical model, statistical assumptions, concerning, the generation, sample data, a mathematical model, description, a system, mathematical concepts and language, natural sciences,  engineering disciplines, social sciences",
      "[関連] 強化学習 [pronunciation] [hiragana or katakana], 関数 [pronunciation] [hiragana or katakana], 予測 [pronunciation] [hiragana or katakana], 期待収益 [pronunciation] [hiragana or katakana], から [pronunciation] [hiragana or katakana], 実行 [pronunciation] [hiragana or katakana], アクション [pronunciation] [hiragana or katakana], 状態で [pronunciation] [hiragana or katakana], その後 [pronunciation] [hiragana or katakana], 特定のポリシー [pronunciation] [hiragana or katakana], 状態アクション [pronunciation] [hiragana or katakana], 値関数 [pronunciation] [hiragana or katakana]",	    
      "[相關] 強化學習，函數，預測，預期回報，從，採取，行動，處於一種狀態，然後遵循，給定的策略，狀態-行動，價值函數",  
    ],
